var songs = [{"title":"All of Me","subtitle":null,"description":"All of Me is a song by American recording artist John Legend from his fourth studio album Love in the Future (2013). Legend co-wrote the song with Toby Gad and co-produced it with Dave Tozer. It is a dedication to Legend's wife Chrissy Teigen. 'All of Me' impacted American mainstream urban radio as the album's third single on August 12, 2013.","yearComposed":2013,"fileName":"All_of_me.pdf","price":5.99,"inventoryQuantity":10,"instrumentTags":"Piano","sourceUrl":"https://musescore.com/user/428051/scores/2162726","publicDomainStatus":"public", "composerId":1,"genreId":1,"photoId":1},
{"title":"Happy Christmas (War is Over)","subtitle":null,"description":"Happy Xmas (War Is Over) is a traditional song with lyrics by John Lennon and Yoko Ono, released in 1971 as a singleby John & Yoko/Plastic Ono Band with the Harlem Community Choir. The lyrics are set to the traditional English ballad 'Skewball'. It was the seventh single release by Lennon outside of his work with the Beatles. The song reached number 4 in the UK, where its release was delayed until November 1972, and has periodically reemerged on the UK Singles Chart, most notably after Lennon's death in 1980, at which point it peaked at number 2. Also a protest song against the Vietnam War, 'Happy Xmas (War Is Over)' has since become a Christmas standard, frequently covered by other artists, appearing on compilation albums of seasonal music, and named in polls as a holiday favourite.","yearComposed":1971,"fileName":"Happy_Christmas.pdf","price":5.99,"inventoryQuantity":10,"instrumentTags":"Piano, Clarinet","sourceUrl":"https://musescore.com/user/3715866/scores/1297511","publicDomainStatus":"public", "composerId":2,"genreId":2,"photoId":2},
{"title":"We Are the champions","subtitle":null,"description":"Artist: Queen - - - - - 'We Are the Champions' is a song by the British rock band Queen, first released on their 1977 album News of the World.[1] Written by lead singer Freddie Mercury, it is one of Queen's most popular songs, and one of rock's most recognisable anthems","yearComposed":1977,"fileName":"We_Are_The_Champions.pdf","price":5.99,"inventoryQuantity":10,"instrumentTags":"Piano","sourceUrl":"https://musescore.com/user/994441/scores/470986","publicDomainStatus":"public", "composerId":3,"genreId":2,"photoId":3},
{"title":"Dream On","subtitle":null,"description":"Artist: Aerosmith - - - -  - 'Dream On' is a power ballad by Aerosmith from their 1973 debut album, Aerosmith.[3] Written by lead singer Steven Tyler, this song was their first major hit and became a classic rock radio staple. Released in June 1973, it peaked at number 59 on the Billboard Hot 100 but hit big in the band's native Boston, where it was the number one single of the year on WBZ-FM, number five for the year on WRKO and number 16 on WMEX (AM)","yearComposed":1973,"fileName":"Dream_On.pdf","price":5.99,"inventoryQuantity":10,"instrumentTags":"Piano","sourceUrl":"https://musescore.com/user/923856/scores/1356306","publicDomainStatus":"public", "composerId":4,"genreId":2,"photoId":4},
{"title":"Lean On Me","subtitle":null,"description":"Lean on Me' is a song written and recorded by American singer-songwriter Bill Withers. It was released in April 1972 as the first single from his second album, Still Bill. It was his first and only number one single on both the soul singles and the Billboard Hot 100.[1] Billboard ranked it as the No. 7 song of 1972.[2] It is ranked number 205 on Rolling Stone's list of 'The 500 Greatest Songs of All Time'.[3] Numerous cover versions have been recorded, and it is one of only nine songs to have reached No. 1 with versions recorded by two different artists.","yearComposed":1972,"fileName":"Lean_On_Me.pdf","price":5.99,"inventoryQuantity":10,"instrumentTags":"Piano, Flute","sourceUrl":"https://musescore.com/user/329141/scores/563016","publicDomainStatus":"public", "composerId":5,"genreId":3,"photoId":5},
{"title":"Can You Feel The Love Tonight","subtitle":null,"description":"Can You Feel the Love Tonight' is a song from Disney's 1994 animated film The Lion King[2] composed by Elton John with lyrics by Tim Rice.[1] It was described by Don Hahn (the film's producer), Roger Allers and Rob Minkoff (the film's directors) as having 'the most diverse history' in the film.[3] It was a chart hit in the UK, peaking at #14 on the UK Singles Chart,[1] and achieved even more success in the U.S., reaching a peak of #4 on the Billboard Hot 100. The song was a number-one hit in France, and it sold 11 million copies World Wide.","yearComposed":1993,"fileName":"Can_you_feel_the_love_tonight.pdf","price":5.99,"inventoryQuantity":10,"instrumentTags":"Piano","sourceUrl":"https://musescore.com/user/206846/scores/931586","publicDomainStatus":"public", "composerId":6,"genreId":4,"photoId":6},
{"title":"Hey Jude","subtitle":null,"description":"Hey Jude' is a song by the English rock band the Beatles, written by Paul McCartney and credited to Lennon–McCartney. The ballad evolved from 'Hey Jules', a song McCartney wrote to comfort John Lennon's son, Julian, during his parents' divorce. 'Hey Jude' begins with a verse-bridge structure incorporating McCartney's vocal performance and piano accompaniment; further instrumentation is added as the song progresses. After the fourth verse, the song shifts to a fade-out coda that lasts for more than four minutes.","yearComposed":1968,"fileName":"Hey_Jude.pdf","price":5.99,"inventoryQuantity":10,"instrumentTags":"Piano","sourceUrl":"https://musescore.com/user/7398241/scores/2236536","publicDomainStatus":"public", "composerId":2,"genreId":2,"photoId":7},
{"title":"Let It Be","subtitle":null,"description":"Let It Be' is a song by the Beatles, released in March 1970 as a single, and (in an alternate mix) as the title track of their album Let It Be. At the time, it had the highest debut on the Billboard Hot 100, reaching number 6. It was written and sung by Paul McCartney. It was their final single before McCartney announced his departure from the band. Both the Let It Be album and the US single 'The Long and Winding Road' were released after McCartney's announced departure from and subsequent break-up of the group.","yearComposed":1970,"fileName":"Let_it_Be.pdf","price":5.99,"inventoryQuantity":10,"instrumentTags":"Piano","sourceUrl":"https://musescore.com/user/229091/scores/216161","publicDomainStatus":"public", "composerId":2,"genreId":2,"photoId":8},
{"title":"Stairway To Heaven","subtitle":null,"description":"Artist: Led Zeppelin - - - - 'Stairway to Heaven' is a song by the English rock band Led Zeppelin, released in late 1971. It was composed by guitarist Jimmy Page and vocalist Robert Plant for the band's untitled fourth studio album (often called Led Zeppelin IV). It is often referred to as one of the greatest rock songs of all time.","yearComposed":1971,"fileName":"Stairway_To_Heaven.pdf","price":5.99,"inventoryQuantity":10,"instrumentTags":"Piano","sourceUrl":"https://musescore.com/user/9006866/scores/1998871","publicDomainStatus":"public", "composerId":7,"genreId":2,"photoId":9},
{"title":"Can't Help Falling In Love With You","subtitle":null,"description":"Aritst: Elvis Presley - - - - -'Can't Help Falling in Love' is a pop ballad originally recorded by American singer Elvis Presley and published by Gladys Music, Elvis Presley's publishing company. It was written by Hugo Peretti, Luigi Creatore and George David Weiss.[2] The melody is based on 'Plaisir d'amour'[4] (1784), a popular romance by Jean Paul Egide Martini (1741–1816). It was featured in Elvis Presley's 1961 film, Blue Hawaii. During the following four decades, it was recorded by numerous other artists, including British reggae group UB40, whose 1993 version topped the U.S. and UK charts, and Swedish pop group A-Teens.","yearComposed":1961,"fileName":"Cant_Help_Falling_In_Love_With_You.pdf","price":5.99,"inventoryQuantity":10,"instrumentTags":"Piano","sourceUrl":"https://musescore.com/user/3295186/scores/2168036","publicDomainStatus":"public", "composerId":8,"genreId":2,"photoId":10},
{"title":"Let It Go (Frozen)","subtitle":null,"description":"Artist: Idina Menzel - - - - 'Let It Go' is a song from Disney's 2013 animated feature film Frozen, whose music and lyrics were composed by husband-and-wife songwriting team Kristen Anderson-Lopez and Robert Lopez. The song was performed in its original show-tune version in the film by American actress and singer Idina Menzel in her vocal role as Queen Elsa. Anderson-Lopez and Lopez also composed a simplified pop version (with shorter lyrics and background chorus) which was performed by actress and singer Demi Lovato over the start of the film's closing credits. A music video was separately released for the pop version.","yearComposed":2013,"fileName":"Let_It_Go_From_Frozen.pdf","price":5.99,"inventoryQuantity":10,"instrumentTags":"Piano","sourceUrl":"https://musescore.com/user/467056/scores/1844401","publicDomainStatus":"public", "composerId":9,"genreId":4,"photoId":11},
{"title":"Dream Is Collapsing","subtitle":null,"description":"Inception: Music from the Motion Picture is the soundtrack to the 2010 film of the same name directed by Christopher Nolan, released under Reprise Records on July 13, 2010. Hans Zimmer scored the film, marking his third collaboration with Nolan following Batman Begins and The Dark Knight. ----- Dream Is Collapsing is the third track on the album Inception: Music from the Motion Picture. It runs for 2:28 minutes. The title is a phrase said by Arthur after waking up from the second dream level (Saito's palace) during the Saito extraction job.","yearComposed":2010,"fileName":"Dream_is_collapsing.pdf","price":5.99,"inventoryQuantity":10,"instrumentTags":"Piano","sourceUrl":"https://musescore.com/user/7018786/scores/1762636","publicDomainStatus":"public", "composerId":15,"genreId":5,"photoId":12},
{"title":"Kyrie from Mozart's Requiem","subtitle":null,"description":"The Requiem Mass in D minor (K. 626) by Wolfgang Amadeus Mozart was composed in Vienna in 1791 and left unfinished at the composer's death on December 5. A completion dated 1792 by Franz Xaver Süssmayr was delivered to Count Franz von Walsegg, who had anonymously commissioned the piece for a Requiem Mass to commemorate the February 14 anniversary of his wife's death.","yearComposed":1791,"fileName":"Kyrie_from_Mozarts_Requiem.pdf","price":5.99,"inventoryQuantity":10,"instrumentTags":"organ, violin, viola, cello, timpani","sourceUrl":"https://musescore.com/danetone/kyriefrommozartsrequiem","publicDomainStatus":"public", "composerId":10,"genreId":6,"photoId":13},
{"title":"Main Theme from Interstellar","subtitle":null,"description":"Interstellar: Original Motion Picture Soundtrack is the soundtrack album to the 2014 film Interstellar directed by Christopher Nolan. The film score is composed by Hans Zimmer who previously scored Nolan's Batman film trilogy and Inception. The soundtrack garnered critical acclaim. Prior to its digital release, it was nominated for an Academy Award and Original Score at the Hollywood Music in Media Awards.[1] The soundtrack was released on November 17, 2014 via the WaterTower label.","yearComposed":2014,"fileName":"Insterstellar_-_Main_Theme.pdf","price":5.99,"inventoryQuantity":10,"instrumentTags":"Piano","sourceUrl":"https://musescore.com/user/9120741/scores/2087541","publicDomainStatus":"public", "composerId":15,"genreId":5,"photoId":14},
{"title":"He's A Pirate","subtitle":null,"description":"He's a Pirate' is a 2003 track composed by Klaus Badelt for the Disney movie Pirates of the Caribbean: The Curse of the Black Pearl. It is featured on the soundtrack album of the film and is used at the beginning of the credits for the film.","yearComposed":2003,"fileName":"Hes_a_pirate.pdf","price":5.99,"inventoryQuantity":10,"instrumentTags":"Piano","sourceUrl":"https://musescore.com/user/7137616/scores/1670081","publicDomainStatus":"public", "composerId":11,"genreId":5,"photoId":15},
{"title":"Two Worlds","subtitle":null,"description":"Two Worlds' is a song by English singer Phil Collins for the soundtrack of Disney's 1999 film Tarzan. The song is the opening song to the movie and is used multiple times throughout the film. It appears four times on the soundtrack: the main version in the film's opening, the reprise, the 'Phil' version in the credits, and as the finale.","yearComposed":2000,"fileName":"Tarzan-two-worlds.pdf","price":5.99,"inventoryQuantity":10,"instrumentTags":"Piano","sourceUrl":"http://pop-sheet-music.com/Files/c9151d4af1da9ef65b12a48ecc1c126f.pdf","publicDomainStatus":"public", "composerId":12,"genreId":4,"photoId":16},
{"title":"Beethoven's Symphony No.5","subtitle":null,"description":"The Symphony No. 5 in C minor of Ludwig van Beethoven, Op. 67, was written between 1804–1808. It is one of the best-known compositions in classical music, and one of the most frequently played symphonies.[1] First performed in Vienna's Theater an der Wien in 1808, the work achieved its prodigious reputation soon afterward. E. T. A. Hoffmann described the symphony as 'one of the most important works of the time'. The symphony consists of four movements. The first movement is Allegro con brio; the second movement is Andante con moto; the third movement is a Scherzo Allegro; the fourth movement is Allegro.","yearComposed":1804,"fileName":"Beethoven_Symphony_No._5.pdf","price":5.99,"inventoryQuantity":10,"instrumentTags":"Piano","sourceUrl":"https://musescore.com/user/24069/scores/128179","publicDomainStatus":"public", "composerId":13,"genreId":6,"photoId":17},
{"title":"Circle of Life","subtitle":null,"description":"Circle of Life'[note 1] is a song from Disney's 1994 animated film The Lion King. Composed by Elton John, with lyrics by Tim Rice,[4] the song was performed by Carmen Twillie (the deep female lead vocals) and Lebo M. (opening Zulu vocals) as the film's opening song.[5] In an interview, Rice said he was amazed at the speed with which John composed: 'I gave him the lyrics at the beginning of the session at about two in the afternoon. By half-past three, he'd finished writing and recording a stunning demo.'[6] Elton John sang a pop version of the song with the London Community Gospel Choir, which was included in the film's soundtrack and made into a music video. 'Circle of Life' was nominated for the Academy Award for Best Song in 1994, along with two other songs from The Lion King: 'Hakuna Matata' and 'Can You Feel the Love Tonight' [7][8] which won the award.","yearComposed":1993,"fileName":"Circle_of_Life.pdf","price":5.99,"inventoryQuantity":10,"instrumentTags":"Piano","sourceUrl":"https://musescore.com/user/1813301/scores/794811","publicDomainStatus":"public", "composerId":15,"genreId":4,"photoId":18},
{"title":"Game of Thrones Theme","subtitle":null,"description":"The music for the fantasy TV series Game of Thrones by the U.S. cable channel HBO is composed by Ramin Djawadi and published by Varèse Sarabande. The soundtrack is instrumental and features one major theme, the Main Title, which accompanies the series' title sequence.","yearComposed":2011,"fileName":"Game_of_Thrones_Theme.pdf","price":5.99,"inventoryQuantity":10,"instrumentTags":"Violin, viola, cello, contrabass","sourceUrl":"https://musescore.com/user/3715101/scores/1343726","publicDomainStatus":"public", "composerId":14,"genreId":7,"photoId":19},
{"title":"Time","subtitle":null,"description":"Inception: Music from the Motion Picture is the soundtrack to the 2010 film of the same name directed by Christopher Nolan, released under Reprise Records on July 13, 2010. Hans Zimmer scored the film, marking his third collaboration with Nolan following Batman Begins and The Dark Knight ------Time is the twelfth and final non-bonus track on the album Inception: Music from the Motion Picture. It runs for 4:35 minutes. The track's theme was written to evoke of a sense of life, and how it is only as important as the dreams which make up our reality. This track plays when Cobb and Saito wake up in the airplane and Cobb finally gets to go home to see his children.","yearComposed":2010,"fileName":"Time_Inception.pdf","price":5.99,"inventoryQuantity":10,"instrumentTags":"Piano","sourceUrl":"https://musescore.com/user/3639786/scores/2093926","publicDomainStatus":"public", "composerId":15,"genreId":5,"photoId":20}]


var composers = [{"firstName":"John","lastName":"Legend"}, //1
{"firstName":"John","lastName":"Lenon"}, //2
{"firstName":"Freddie","lastName":"Mercury"}, //3
{"firstName":"Steven","lastName":"Tyler"}, //4
{"firstName":"Bill","lastName":"Withers"}, //5
{"firstName":"Elton","lastName":"John"}, //6
{"firstName":"Jimmy","lastName":"Page"}, //7
{"firstName":"Hugo","lastName":"Peretti"}, //8
{"firstName":"Kristen","lastName":"Anderson-Lopez"}, //9
{"firstName":"Wolfgang","lastName":"Mozart"}, //10
{"firstName":"Klaus","lastName":"Badelt"},  //11
{"firstName":"Phil","lastName":"Collins"}, //12
{"firstName":"Ludwig","lastName":"Beethoven"}, //13
{"firstName":"Ramin","lastName":"Djawadi"}, //14
{"firstName":"Hans","lastName":"Zimmer"}] //15


var genres = [{"genreName":"Pop"},
{"genreName":"Rock"},
{"genreName":"Soul"},
{"genreName":"Disney"},
{"genreName":"Film Score"},
{"genreName":"Classical"},
{"genreName":"Television Soundtrack"}]

var photos = [{"isLocal":"false","localFileName":null,"externalUrl":"https://upload.wikimedia.org/wikipedia/en/thumb/4/4f/Allofmejohnlegend.jpg/220px-Allofmejohnlegend.jpg"},
{"isLocal":"false","localFileName":null,"externalUrl":"https://upload.wikimedia.org/wikipedia/en/thumb/a/a9/Happy_Xmas_%28War_is_Over%29.jpg/220px-Happy_Xmas_%28War_is_Over%29.jpg"},
{"isLocal":"false","localFileName":null,"externalUrl":"https://upload.wikimedia.org/wikipedia/en/thumb/5/5a/Wearethechampions.jpg/220px-Wearethechampions.jpg"},
{"isLocal":"false","localFileName":null,"externalUrl":"https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/DreamOnsingle.jpg/220px-DreamOnsingle.jpg"},
{"isLocal":"false","localFileName":null,"externalUrl":"https://upload.wikimedia.org/wikipedia/en/thumb/0/07/LeanOnMe_Single_cover.jpg/220px-LeanOnMe_Single_cover.jpg"},
{"isLocal":"false","localFileName":null,"externalUrl":"https://upload.wikimedia.org/wikipedia/en/thumb/3/35/Elton_john-can_you_feel_the_love_tonight_s_1.jpg/220px-Elton_john-can_you_feel_the_love_tonight_s_1.jpg"},
{"isLocal":"false","localFileName":null,"externalUrl":"https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/Hey_Jude_Beatles.jpg/220px-Hey_Jude_Beatles.jpg"},
{"isLocal":"false","localFileName":null,"externalUrl":"https://upload.wikimedia.org/wikipedia/en/thumb/d/d7/Letitbe_single.jpg/220px-Letitbe_single.jpg"},
{"isLocal":"false","localFileName":null,"externalUrl":"https://upload.wikimedia.org/wikipedia/en/thumb/6/6a/Stairwaytoheavenpromo.jpg/220px-Stairwaytoheavenpromo.jpg"},
{"isLocal":"false","localFileName":null,"externalUrl":"https://upload.wikimedia.org/wikipedia/en/thumb/3/3d/Elvis_-_Rock_a_Hula.jpg/220px-Elvis_-_Rock_a_Hula.jpg"},
{"isLocal":"false","localFileName":null,"externalUrl":"https://upload.wikimedia.org/wikipedia/en/thumb/8/89/Frozen_2013_soundtrack.png/220px-Frozen_2013_soundtrack.png"},
{"isLocal":"false","localFileName":null,"externalUrl":"https://upload.wikimedia.org/wikipedia/en/thumb/1/18/Inception_OST.jpg/220px-Inception_OST.jpg"},
{"isLocal":"false","localFileName":null,"externalUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/K626_Requiem_Mozart.jpg/290px-K626_Requiem_Mozart.jpg"},
{"isLocal":"false","localFileName":null,"externalUrl":"https://upload.wikimedia.org/wikipedia/en/thumb/c/ca/Interstellar_soundtrack_album_cover.jpg/220px-Interstellar_soundtrack_album_cover.jpg"},
{"isLocal":"false","localFileName":null,"externalUrl":"https://upload.wikimedia.org/wikipedia/en/thumb/f/f9/The_Curse_of_the_Black_Pearl_Soundtrack.jpg/220px-The_Curse_of_the_Black_Pearl_Soundtrack.jpg"},
{"isLocal":"false","localFileName":null,"externalUrl":"https://upload.wikimedia.org/wikipedia/en/thumb/d/d5/Two_Worlds_single.jpg/220px-Two_Worlds_single.jpg"},
{"isLocal":"false","localFileName":null,"externalUrl":"https://upload.wikimedia.org/wikipedia/commons/6/6a/Beethoven-Deckblatt.png"},
{"isLocal":"false","localFileName":null,"externalUrl":"https://upload.wikimedia.org/wikipedia/en/5/5a/Circle_of_Life.jpg"},
{"isLocal":"false","localFileName":null,"externalUrl":"https://upload.wikimedia.org/wikipedia/en/thumb/d/d8/Game_of_Thrones_title_card.jpg/250px-Game_of_Thrones_title_card.jpg"},
{"isLocal":"false","localFileName":null,"externalUrl":"https://upload.wikimedia.org/wikipedia/en/thumb/1/18/Inception_OST.jpg/220px-Inception_OST.jpg"}]

module.exports = {
	songs:songs,
	composers:composers,
	genres:genres,
	photos:photos
}